version: "3.7"

services:
    app:
        build: docker
        network_mode: host
        ports:
            - 3000
        volumes:
            - .:/data
        environment:
            - NODE_ENV=development
            - CI=true 